### ISSUE TITLE
Retrieve business type

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#105]
For sales persons at SumUp, the business type is a very important indicator. Retrieving the business type from the Google Maps API is generally possible. This should be implemented now.

### Done?
The business type can be retrieved manually and / or is retrieved automatically, when other Google Maps API data is collected.

**Comment by soapyheas** [comment]
Updated using branch feature/71-gpt-as-data-source

The available place types are not comprehensive, unless we use the Place Details (NEW) API, which uses HTTP GET Requests:
https://developers.google.com/maps/documentation/places/web-service/place-details#place-details-example

**Comment by soapyheas** [comment]
Edit:

We are able to access the extended business types, though not many businesses have tagged their place with appropriate business types.
Documentation for types of tags a business can have is available here:
https://developers.google.com/maps/documentation/places/web-service/supported_types
