### ISSUE TITLE
Download Reviews

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#106]
For further analysis, we need to download reviews from the Google Maps API.

### Done?
* The reviews for a given entity are retrieved manually and / or automatically, when other Google Maps API data is collected.
* The reviews are stored in a place and format, so that they can be analyzed easily (e.g. in a separate database table or as JSON files).

**Comment by ruchita-nathani** [comment]
Merged the branch for this issue in the pair programming with Sophie and Lucca, so no separate PR.
