### ISSUE TITLE
Fix bug in Google pipeline step

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#114]
There is a bug:

> The app crashes in google_places.py, line 81. 
> 
> How to reproduce:
> 
> 1. run app
> 2. type following console inputs 
> 
> 
>             - 1
>         
>             - 1
>             
>             - 4
>             
>             - y
>             
>             - n
>             
>             - n
>             
>             - y
>             
>             - 15
> 

### Notes
The cause might be that `finish` runs regardless of whether the pipeline step has actually run.

### Acceptance Criteria
* The bug is fixed

**Comment by luccalb** [comment]
Test cases have to be adjusted accordingly. Also it might make sense to add new test cases that validate the behaviour if a single step fails. Additionaly we could create a `StepRequirementsNotSatisfied` Exception to raise when specific columns are missing.

**Comment by luccalb** [comment]
Looking to fix this in #121
