### ISSUE TITLE
Implement the import for frame diff (Library 2)

### ISSUE THREAD

**Issue by Freeze-FF** [amosproj/amos2023ws06-sales-lead-qualifier#12]
## User story
1. As a user 
2. I want / need to load two video files from the file system   
3. So that the video loaded into the program can be used in the Kotlin program for further processing.  

## Acceptance criteria
* The system must provide an graphical user interface or API for the user to select two video files from the file system.
* The system should only support and recognize video files that have a lossless compression 
* The video files should be loaded into the program, otherwise a helpful error handling should be triggered
* For the next processing steps, the the video files must be available/ accessible in the Kotlin program.

## Definition of done (DoD)
* All specifiec acceptance criterias are met 
* The feature branch is merged into the main branch and then closed
* The code is clearly documented 

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by luccalb** [comment]
wrong project :D
