### ISSUE TITLE
Document pipeline steps

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#135]
Keeping the documentation for pipeline stages updated can be quite hard.
Notably, we currently have at least 3 different locations, where related documents are stored:
* https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/blob/main/Documentation/Data-Field-Definition.md
* https://docs.google.com/document/d/1eqhv6EWOHwi9IpK1nO6fTigyr3mk3PW8y2JP7seFtsw/edit
* https://docs.google.com/spreadsheets/d/17W1Koj2aMCUXyq_zYtjvIA3FRmtviDaxpYYIY7xwWWA/edit

To tackle this problem, we want to document our pipeline stages directly in the source code and use this as the single source of truth.

### Implementation notes
* [pydoc](https://docs.python.org/3/library/pydoc.html) might be a good choice but other approaches should also be considered (e.g. [decorators](https://peps.python.org/pep-0318/) could double for documentation and logical purposes).
* As a first step, only the documentation for existing pipeline stages should be added. Future items could then generate e.g. HTML or PDF documents on that data basis automatically.

### Acceptance Critera
* documentation for existing pipeline stages should be added in an uniform format

**Comment by luccalb** [comment]
@soapyheas I hope you don't mind if I jump in on this.
Created branch docs/135-document-pipeline-steps

- [ ] GooglePlaces
- [ ] GooglePlacesDetailed
- [ ] AnalyzeEmails
- [ ] AnalyzeReviews
- [ ] GptSummarizer
- [ ] PreprocessPhonenumbers
- [ ] Regionalatlas
- [ ] ScrapeAddress
- [ ] SocialMediaApi

**Comment by soapyheas** [comment]
I was going to do this today, but I guess it's been done. Cheers @luccalb !
