### ISSUE TITLE
Find an alternative for language_tool_python

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#148]
#91 can not currently be merged because it makes use of language_tool_python which is under a copyleft license.

### Acceptance Criteria
* An alternative for language_tool_python has been found that complies to our license restrictions.

**Comment by rbbozkurt** [comment]
For the most accurate grammer check, we should be checking the original text of reviews not the to english translated ones, since translated versions do not contain any errors. Therefore most fit package should be supporting multilanguage configurations.

**Comment by rbbozkurt** [comment]
According to [Stackoverflow](https://stackoverflow.com/a/77476879), Gingerit is no longer supported by PyPi.
