### ISSUE TITLE
Find data for leads which we currently do not have data about

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#149]
### Ideas
* Website parsing
* Better processing of Google results
* whatever else

### Acceptance Criteria
* Research results on how we can find data for additional leads
* Possibly some example code (optional)
* List of additional resources that we might need (e.g. API keys)

**Comment by luccalb** [comment]
GooglePlaces can be improved by:

- Adding full name search
- Checking all results (not just the first one) from all search methods and trying to match them by place_id
- If no matching place_id was found, try to figure out the best result some other way

**Comment by ur-tech** [comment]
Andi's Idea: Using other Sources like Handelsregister to check lead name / address
