### ISSUE TITLE
Inspect lead "neighbors"

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#152]
For SumUp it will be interesting to know about what other businesses there are in the vicinity of a given lead. To provide the data basis for this, a "nearby search" based on the GoogleMapsAPI should be implemented.

### Implementation Note
To save API costs, consider using the coarse location only (i.e. ZIP-Code). This way one query would be enough for multiple leads that are close to each other.

### Acceptance Criteria
* Relevant data is cached as JSON, similar to how reviews are being handled.
* Optional: Some aggregated form of this data is stored in the CSV file, ready for use by SumUp.
* Pipeline stage has been documented.

**Comment by ur-tech** [comment]
Berkay: https://googlemaps.github.io/google-maps-services-python/docs/#googlemaps.Client.places_nearby

**Comment by soapyheas** [comment]
Todo:

- [ ] Retrieve the location from Google Places (Embedded field, might need to restructure to obtain info)
- [ ] Call the nearby places API using lat/long tuple, and filter for same business type as current business
- [ ] Save into json format
- [ ] Store number of similar businesses in the csv

**Comment by luccalb** [comment]
We probably need to get the business location as coordinates from the geometry field: 

```{json}
"geometry":
          {
            "location": { "lat": -33.8599358, "lng": 151.2090295 },
            "viewport":
              {
                "northeast":
                  { "lat": -33.85824377010728, "lng": 151.2104386798927 },
                "southwest":
                  { "lat": -33.86094342989272, "lng": 151.2077390201073 },
              },
          },

```
