### ISSUE TITLE
Data Field Definition

### ISSUE THREAD

**Issue by taniakraft** [amosproj/amos2023ws06-sales-lead-qualifier#17]
Define and document the main data fields required for our project, including 
- name, 
- first name (owner), 
- last name (owner), 
- telephone number, 
- email of the business.

Task: 
- Create a data specification document to record the details of each data field. For exampls, include the following information for each field:
Field Name
Data Type (e.g., text, number, date)
Description (brief explanation of the field)
Validation Rules (if any, such as required format or constraints)
Source of Data (where the data will come from)
Sample Data (if available)

**Comment by Tims777** [comment]
Related: #35
