### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by luccalb** [amosproj/amos2023ws06-sales-lead-qualifier#173]
Over time, due to strategy and priority changes, some code has accumulated that isn't used anywhere in our pipeline. It would be helpful for readability of our code to remove those classes/methods.

**Acceptance Criteria**

- [ ] unused code has been identified, reviewed and removed if possible
- [ ] unused dependencies have been identified and removed

**Comment by Tims777** [comment]
See #107
