### ISSUE TITLE
Bug: Incorporating Regional Atlas doesn't let the pipeline run till the end

### ISSUE THREAD

**Issue by ultiwinter** [amosproj/amos2023ws06-sales-lead-qualifier#184]
Problem:
When the pipeline includes the regional atlas step, it works until saving the snapshots. In pipeline.py, it works only until the "finally:" (line 60), but it doesn't continue to "self.df = self.df.replace(np.nan, None)" nor the rest of the code. 
The pipeline works flawlessly if the regional atlas is not included.

Done?
Pipeline works flawlessly including the regional atlas.

**Comment by Tims777** [comment]
This bug description indicates that the RegionalAtlas-Step does presumably throw some generic execption which is consequently not catched by the line `except StepError as e`.
