### ISSUE TITLE
Preprocessing of collected lead data

### ISSUE THREAD

**Issue by taniakraft** [amosproj/amos2023ws06-sales-lead-qualifier#19]
Data coming from BDC is potentially unsuitable for being processed in EVP. Plan and implement any necessary data transformations to address this.

### User Story
As developers you want to limit coupling of BDC and EVP so that changes in one component do not require changes in the other component as well. Therefore data coming from BDC (which is unsuitable for direct processing by a machine learning algorithm) needs to be preprocessed in a flexible way.

### Implementation notes
See comment by @ultiwinter7 for more details

### Acceptance Criteria
* Preprocessing pipeline has been implemented (if Devs agree that they want one).
* Preprocessed data is ready to be used as input for ML training.
  * This will most likely require all the steps outlined by @ultiwinter7 below.
  * Devs have to agree on what steps are actually necessary for now.
  * Steps might be very basic for now, as long as this does not prohibit training entirely.

**Comment by ultiwinter** [comment]
Points to address in the data preprocessing(feel free to add more):

1. Convert the categorical data  into numerical data for the AI model.
2. Removal/handling of missing values
3. Addressing the outliers
4. Normalization/standardization of the data
5. Data augmentation (optional?): it is highly important if the number of features are limited
6. Handling imbalanced data

Preprocessing of the data highly depends on the data itself. Waiting for #17
