### ISSUE TITLE
Agree on a branching strategy

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#2]

**Comment by ruchita-nathani** [comment]
**Here I have added a branching strategy and its description.**

**main**: It contains fully stable production code

- **dev**: It contains stable under-development code
   - **epic**: It contains a module branch. Like high level of feature. For example, we have an authentication module then we can create a branch like "**epic/authentication**"

      - **feature**: It contains specific features under the module. For example, under authentication, we have a feature called registration. Sample branch name: "**feature/registration**"
      - **bugfix**: [It contains bug fixing during the testing phase for example "**bugfix/validate-for-wrong-user-name**"

**Comment by luccalb** [comment]
i like to start a feature/bugfix branch name with the issue number e.g. `3-fix-bug`.

**Comment by felix-zailskas** [comment]
I like the strategy. Towards the point of @luccalb I would suggest the naming:
"bugfix/<issue-number>-<description-of-bug>" e.g. "bugfix/3-validate-for-wrong-user-name"

This way it is listed in the bugfix "branching directory" and includes the issue number

**Comment by NicoHambauer** [comment]
Cool progress here! The rules and strategy makes sense and seems solid to me!
I guess additionally one can also link an issue to a branch (see image below).

<img width="293" alt="image" src="https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/assets/58194361/c15835ed-8550-413a-b928-c69c23ff5b18">

**Comment by Tims777** [comment]
@ruchita-nathani as everybody seems to be happy with the branchint strategy, maybe you can write it down as Markdown (or similar) into our repositories Documentation folder
