### ISSUE TITLE
Research on external data sources

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#21]
**Quote from project description:**
The following are examples of public data sources only and should not constrain the thinking and creativity of the team:
* Google-maps API
* Google Search API
* Domain registration service
* facebook/instagram
* ChatGPT
* …

These could yield data like:
* Customer Reviews and extracted information (sentiment, type of business, do they have staff, tables to be served, …)
* Name, Address, type of the business (competition in the area, demographic, …)
* Do they already have a web-presence or a web-shop
* …

**Comment by Tims777** [comment]
The data providers should target the European market (i.e. GB, Spain, Germany, Italy, France).

**Comment by soapyheas** [comment]
@luccalb This looks good! We could add another metric where if the company is worth contacting, but won't generate enough revenue to warrant a call from a salesperson (90% of companies according to Marc if I recall), we can keep track of that so they could use this information to instead redirect them to an automated/self-directed signup process.

**Comment by ur-tech** [comment]
I don't know how much of that job would be part of the AI team, but we could combine your ideas. 
Create a model, maybe first decision trees or clustering because we get so much categorical data at the beginning (and no revenue). After we get revenue data of the leads we can "upgrade" by using regression (linear / logistic).  And based on the results of the models we suggest process decisions.

**Comment by rbbozkurt** [comment]
Recently I have heart about new "chatGPT Browse with Bing" from openAI, which now can make searches on Internet to provide answers unlike chatGPT 3.5. One can basically ask GPT a question about an individual and GPT searches other sources like linkedIn and provides an answer. Please follow the [link](https://help.openai.com/en/articles/8077698-how-do-i-use-chatgpt-browse-with-bing-to-search-the-web?q=browse+with+bing) for more info.
