### ISSUE TITLE
Agree on technologies (Linter, Programming Language, etc)

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#3]
Discuss with industry partner on which technologies to use:
* Programming Language(s)
* Linter / Formatter for specific languages
* Hooks
* Programming Environment

Tasks:
- install and setup pre-commit (black, isort, prettier)
- install and setup PipEnv with empty environment (python version 3.10, for stability and being supported for a long time)
- update README.md to reflect new contribution workflow

**Comment by NicoHambauer** [comment]
Hi there! There are updates in the new detailed project description i just sent to you guys on slack

**Comment by ur-tech** [comment]
Programming Languages: Python (base-data collector, expected value predictor) and Go (collector)
