### ISSUE TITLE
Create software bill of materials

### ISSUE THREAD

**Issue by NicoHambauer** [amosproj/amos2023ws06-sales-lead-qualifier#31]
Fill in the bill of materials section of your planning document.
* You can limit your bill of materials to your first-level dependencies
* You can use an alternative format; consider using your build tool

**Comment by ur-tech** [comment]
In the "planning-document.pdf"
(https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/blob/dev/Deliverables/sprint-02/planning-document.pdf)

**Comment by ur-tech** [comment]
In the "planning-document.pdf"
(https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/blob/dev/Deliverables/sprint-02/planning-document.pdf)
