### ISSUE TITLE
Implement Controller skeleton

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#36]
Our two main components (BDC & EVP) need to be coordinated in some way.
This tasks aims to implement a basic form of such coordination.

The following possible solutions were brought up during our meeting:
* Central _Controller_ component
* Web-hook driven approach

However, the consensus was, that the controller would be the easier way to implement this, so this is probably where to start.

**Comment by rbbozkurt** [comment]
The controller component is crucial for coordinating the flow of data and interactions between the other components: EVP, BDC. To succesfully manage the communication, it should be designed by following concepts:

**1. Orchestration:** The primary role of controller is to control the workflow and interaction between EVP and BDC.
**2. Message Broker:**  Implementing a message broker or queue system ensures reliable message delivery. The controller enqueue message for the other components and dequeues responses.
**3. Request - Response Pattern:** The controller should use a pattern for communication. It send a request to BDC and waits for response containing the unique ID, and then forwards this ID to the EVP. Once the prediction is done, it retrieves the result.
**4. Error Handling:** Error handling and retries should be implemented to manage issues that may occur during communication between components. 
**5. Data Validation :** The controller should perform data validation as needed to ensure that the data being passed between components is in the expected format. 
**6. Authentication and Authorization:** Security measures, such as authentication and authorization must be ensured to prevent unauthorized access to the components and the data they handle. 
**7. Asynchronous Processing:** The Controller can support asynchronous processing, where it sends requests and periodically checks for responses.

**Comment by Tims777** [comment]
Seems like a very comprehensive list to me.

**Comment by rbbozkurt** [comment]
I thought the work flow of controller for the beginning as following : 


![Image](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/assets/45459787/e9e869d9-2d2a-4f82-9f05-9148c3014dee)
