### ISSUE TITLE
Agree on team name

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#5]

**Comment by felix-zailskas** [comment]
- 1 Serious name
- 1 Funny name

**Comment by ur-tech** [comment]
Sum Insights

**Comment by felix-zailskas** [comment]
Here is the Form for choosing the Name. Please answer only once and rank all possible options. 
I will evaluate the answers on Monday the 23.10.  at 13:00 so we have enough time to create a fitting logo and the t-shirts, so please answer until then. 

https://forms.gle/eGDCFpuAwS4LBHdL9

**Comment by felix-zailskas** [comment]
The voting resulted in the following points for each proposed name:
(44, 'Sum Insights')
(42, 'LeadGen')
(36, 'PB&J')
(36, 'BreakDown')
(29, 'The Sum')
(23, 'Awful Screw')

The team name is "Sum Insights"
