### ISSUE TITLE
Document research results

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#53]
For future development it will be helpful, if you can easily refer to your previous research results.
Also this can be used to give other people (especially from SumUp) a quick overview of our (possibly innovative) ideas.

### Acceptance Criteria
All relevant ideas that are spread across issues (e.g. [#21](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/issues/21#issuecomment-1780722786)) or that may linger on some other platform (e.g. Slack) should be written down as Markdown and contained within our repository.

**Comment by ur-tech** [comment]
- [ ] Pipfile-lock merge conflict 
- [ ] Pipeline: How to add a data source to the pipeline? @soapyheas 

# Data Sources
- [ ] Facebook
- [ ] Instagram
- [ ] GPT
- [ ] TikTok
- [ ] Twitter
- [ ] Deutschland API

**Comment by ur-tech** [comment]
https://docs.google.com/document/d/1eqhv6EWOHwi9IpK1nO6fTigyr3mk3PW8y2JP7seFtsw/edit#heading=h.fbsz5dj3y1hl

**Comment by Tims777** [comment]
See #135 
To not overlap both issues, this issue here should only focus on documenting research results and ideas that are not covered by #135.
