### ISSUE TITLE
Implementation of a Logger module

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#56]
As we are working with threads and potentially will add containers to our setup, we should log information in our application using a logger and not just to stdout.
This will also help us with debugging and detecting errors when they occur.

### Done?
* A logging framework has been decided on.
* Logger has been set up (including the possible log levels and other configs)
* Logs are written to some defined place (possibly a dashboard available in some cloud service)
* Optional: All `print` statements have been replaced with log messages of the appropriate level

**Comment by felix-zailskas** [comment]
Will start this due to quality of life. and low complexity
