### ISSUE TITLE
Design logo and T-shirt

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#6]
If conversion to vector graphics is needed, ask Nico

**Comment by felix-zailskas** [comment]
Andreas asked that we could incorporate the SumUp logo into our logo.

**Comment by rbbozkurt** [comment]
Here you can find the table to put on your size for T-Shirts: 
https://docs.google.com/spreadsheets/d/1nkOh5xcn1sA9c-8aCx9MyUHdG88xRGl_kjxZt3iZisM/edit?usp=sharing

**Comment by NicoHambauer** [comment]
Hi Berkay @rbbozkurt ,
I think we do not have write access yet.

**Comment by rbbozkurt** [comment]
Besides our [t-shirt size table](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/issues/6#issuecomment-1775075379), according to [homework 1](https://docs.google.com/document/d/14xj_KeAx0tCbh7b4SJmDOY8tlpWwSrZO_i_XRDVOtk0/edit ), every individual also need to submit t-shirt preferences to the [survey](https://docs.google.com/forms/d/e/1FAIpQLSdNzNjrllHA1DU0wtt8yknHIev8BDitzaq9wV8jMp2I6_eg9g/viewform).

**Comment by rbbozkurt** [comment]
According to responses chart below, the most picked logo is "Logo 3" with 50%:



![Image](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/assets/45459787/7b37f761-599f-41b9-83d9-a052daad89bf)


Logo 3 (on white background):


![Image](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/assets/45459787/d32f256b-7a92-4998-9f80-ccd2451866b7)


Logo 3 (on black blackground):


![Image](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/assets/45459787/2d960fb5-0ccd-47f0-bebe-1eec83759173)

**Comment by rbbozkurt** [comment]
You can check the t-shirt designs with the [link](https://www.shirtinator.de/loadBasket/Wgfl6csWaoA).
