### ISSUE TITLE
Investigate our testing setup

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#67]
We do have an automatic testing framework set up as part of our Git workflow which is working quite fine. However, this framework does currently contain only two test-files which might indicate, that our code coverage is not quite as good as it could be.

Therefore an investigation shall be made to see in how far our current testing framework can be improved.

### Acceptance Criteria
* Investigations have been made in how far our testing framework can be improved.
* (Larger) possible improvements have been brought up so that items can be created for them.
* Optional: Smaller possible improvements have been implemented directly (instead of documenting them) where this makes sense.

**Comment by felix-zailskas** [comment]
Testing improvements:

Pipeline:
- Is tested

Steps:
- analyze_emails (easy)
    - Can be unit tested as there is no API call
    - Create test file with certain names and emails
    - Test that correct columns are created
    - Test that combinations of domains and names are correctly processed
- analyze_reviews (difficult)
    - Fetches reviews from database => might be hard to mock
    - Potential call to GPT API
- google_places_detailed and google_places (difficult)
    - The whole logic depends on the google API call => hard to mock and isolate
- gpt_summarizer (difficult)
    - The whole logic depends on GPT API call
- hash_generator (easy)
    - No API calls
    - Create testing data and pregenerate ground truth hashes
    - Compare hashes generated by the step and ground truth data
- preprocess_phonenumbers (moderate)
    - No API calls
    - Could create testing data with ground truth outputs like country, area, some invalid, etc.
    - Tested data could grow large if we want to be thorough
    - Would be testing mostly the phonenumbers package we use and not our logic
    - Might still be good to ensure that we get expected data from the package
- regionalatlas  (difficult)
    - Theoretically depends on API but we downloaded the data it uses
    - Could create some testing data and then get ground truth from the file we use
    - Tests might need to be adjusted when the merged_geojson file is updated
    - Seems tedious to create testing and ground truth data
- scrape_address (difficult)
    - Depends on the websites to not change 
    - Could set-up example websites that are only live during the test and are scraped. There would then either contain the searched data or not ensuring that certain patterns can be recognised by our code.
    - A lot of work but doable
- search_offenregister (difficult)
    - Logic fully depends on API call
- social_mdeia_api (difficult)
    - Fully depends on API call
    - Not really used by us as we abandoned Facebook as a source => might want to remove this step

Repository classes:
- Local repository
    - Seems unit testable
    - Would need to create specific test input files and inject them into the class
    - Call certain method and ensure the file is created (on save methods) or that data has been loaded (on load methods). Possibly extend this to also investigate the contents of the saved/loaded data
- S3 repository
    - Harder to test as it is fully intertwined with the connection to the S3 repository
    - Needs access key just for testing with certain rights
    - Would probably need to set up a testing bucket
    - Populate with certain data and check if files have been created/ downloaded
    - Possibly extend to check file contents

Console utils:
- Testable if we can mock user input (which should be fairly easy, unit test module provides possibility to mock this)
- Very straight forward

Demos:
- Perhaps a test of the form if input assert output (in string form, this seems like it gives little value)

Pipeline utils:
- Testable
- Create test json pipeline configs and load them
- Assert that the resulting Pipeline has all requested steps

EVP:
- Could test constructor; I.e. if requested model X the predictor is actually model X => error on unsupported model
- Testing correct training and prediction seems hard. We could have a dummy dataset and ensure that training runs at all if the data is present. Not sure how much value this gives.

Logger:
- Does not seem like we need to test this

Preprocessing:
- Could create input data and ensure that certain values are converted correctly 
- Could help ensure that edge cases are correct
- Might take a lot of effort

**Comment by Tims777** [comment]
Very nice and comprehensive list 👍️
