### ISSUE TITLE
GPT as Data Source

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#71]
For SumUp and the training of our AI model it is beneficial, if we can aggregate information from a multitude of different data sources.
For an overview of current data sources see here: [Data Source Table](https://docs.google.com/spreadsheets/d/17W1Koj2aMCUXyq_zYtjvIA3FRmtviDaxpYYIY7xwWWA/edit)

### Done?
* Required fields (orange) in Data Sources table have been filled out
* Implementation is able to retrieve supported features that are not marked as unimplemented

**Comment by Tims777** [comment]
Taken from #50:

**- GPT-3**
 - **Overview**: he GPT-3 API is the most widely known and used. It offers access to the powerful language model, GPT-3, which can generate text, answer questions, summarize content, and more. The API provides various endpoints for different tasks, including completion, search, and conversation.
  - **Features**: Customizable prompts, adjustable parameters for response control (like temperature and max tokens), and a choice of different models under the GPT-3 umbrella.
  - **Usage Limits**: The API has usage limits based on the subscription plan. OpenAI offers both free and paid plans with varying levels of access and usage limits.
 - **Python Integration**: OpenAI provides an official Python client library for the GPT-3 API. This library simplifies authentication, request making, and response handling. It's well-documented and easy to use.

**- Fine-Tuning GPT-3 API**
  - **Overview**: OpenAI also offers the capability to fine-tune GPT-3 models. This allows developers to train the model on specific datasets to better suit their unique use cases.
  - **Python Integration**: The fine-tuning process can be managed using the same Python client library as the standard GPT-3 API.
 
**- GPT-4 API**
- **Overview**: The GPT-4 API extends the functionalities of GPT-3, offering more advanced capabilities, a larger context window, and improved response accuracy.
- **Access**: Initially, access to the GPT-4 API was limited to ChatGPT Plus subscribers, but it has been gradually opening up for wider usage.
- **Python Integration**: The integration method is similar to GPT-3, using the same Python client library provided by OpenAI.


**- General Points for OpenAI's GPT APIs**
  - **Authentication**: Access to these APIs requires an API key provided by OpenAI. This key is used for authenticating requests.
  - **Documentation and Support:** OpenAI provides comprehensive documentation, including guides on how to use the APIs with Python.
  -  **Compliance and Guidelines**: Users of the API must comply with OpenAI's use-case policies and guidelines.

**_GPT3 API:_** GPT3 basic structure implemented (yet to be pushed), however there have been many problems with experimenting with the free API. Max RPM is 3, and max RPD is 200. Further, the amount of free credits is only $18. It would be worth asking SumUp for the GPT API key (if they have one).

**_Bing Search API:_** I found that GPT wasn't helpful with providing additional data on companies we have extracted using the Google API. However, I thought about using its ability to synthesise information. In a way to mimic the Bing GPT search extension (which doesn't have an API), we could use the Bing Search API to retrieve online information from social media etc, then feed the results into GPT. However, I also had trouble with accessing the Bing Search API free trial to experiment with this.

**Comment by soapyheas** [comment]
**Updates:**
* GPT API key retrieved from Andi. Send me a message on slack to receive the key.
* GPT usage pushed to branch feature/71-gpt-as-data-source-sophie for @rbbozkurt review. Updates can be made using the gpt_3.py file (though I ended up using the gpt-4 model).
* Need to decide if GPT is useful to continue pursuing. Could be good as a data validation tool

**Comment by rbbozkurt** [comment]
Currently we do have two different use-case approaches for GPT:

- [ ] `GPTExtractor` : Using GPT to fill in the gaps occured after other steps.

  - iterate over columns and fill the gaps if possible.
  - The data we get from GPT may not be 100% reliable, but worth to try. 

- [ ] `GPTSummarizer` : Using GPT to write a 2-3 sentences long summary for salesperson

  - Need to extract lead's website, if there any, parse it and pass it to GPT.

Both of the approaches are feasible, we can create 2 different GPT steps like "`GPTExtractor`" and "`GPTSummarizer`"

**Comment by Tims777** [comment]
Closing this, as fundamental steps have already been completed. See [#77](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/issues/77) for continuation.

**Comment by Tims777** [comment]
Related code can be found in [feature/71-gpt-as-data-source](https://github.com/amosproj/amos2023ws06-sales-lead-qualifier/tree/feature/71-gpt-as-data-source) as of now
