### ISSUE TITLE
Lookup of commercial e-mail adresses

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#73]
For SumUp and the training of our AI model it is beneficial, if we can aggregate information from a multitude of different data sources.
For an overview of current data sources see here: [Data Source Table](https://docs.google.com/spreadsheets/d/17W1Koj2aMCUXyq_zYtjvIA3FRmtviDaxpYYIY7xwWWA/edit)

### Done?
* Required fields (orange) in Data Sources table have been filled out
* Implementation is able to retrieve supported features that are not marked as unimplemented

**Comment by luccalb** [comment]
Added the following fields during the `AnalyzeEmails` Steps (formerly `EnrichCustomDomains`):

- `email_valid`: result of email check
- `first_name_in_account`: indicator if first name is part of email account
- `last_name_in_account`: indicator if last name is part of email account

I plan on using this information for better google searches. E.g. if only the last name (or no name) is present, that could indicate a business name (malermeister.meyer@gmx.de) while max.muster@gmail.de will likely not yield business results.
