### ISSUE TITLE
Facebook & Instagram as Data Source

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#75]
For SumUp and the training of our AI model it is beneficial, if we can aggregate information from a multitude of different data sources.
For an overview of current data sources see here: [Data Source Table](https://docs.google.com/spreadsheets/d/17W1Koj2aMCUXyq_zYtjvIA3FRmtviDaxpYYIY7xwWWA/edit)

### Done?
* Required fields (orange) in Data Sources table have been filled out
* Implementation is able to retrieve supported features that are not marked as unimplemented

**Comment by Tims777** [comment]
Taken from #50:

**- Facebook API**
 - **Official API**: The Facebook Graph API allows access to data on Facebook, including user profiles, groups, posts, and more. It's a comprehensive API with extensive documentation.
 - **Python Integration**: Python's `facebook-sdk` library is a popular choice for interacting with the Facebook Graph API.

**- Instagram API**
-  **Official API**: Instagram Graph API allows for managing media objects, reading data, and performing actions on behalf of Instagram Business Accounts. However, it has limitations for personal accounts.
- **Python Integration**: There are Python libraries like `instagram_private_api` for personal accounts, but they are unofficial and may have limitations or risks.

**_Facebook Graph API:_** After implementing Facebook Graph API on branch feature/social-media-api, unfortunately, Facebook Graph API does not allow getting the users' id, which is required to get more info about the user. The access to this functionality has been limited and restricted in many cases. Graph API documentation: https://developers.facebook.com/docs/graph-api

**_Instagram API:_** instagram_private_api API is not officially supported by Instagram and using it violates Instagram's terms of service.

**Comment by luccalb** [comment]
Does this mean that Instagram is a dead end, as we can't get the users explicit permission for data gathering?

**Comment by Tims777** [comment]
We will see, once that we have the Facebook API token, which apparently does also allow some (basic?) Instagram queries as well

**Comment by Tims777** [comment]
Currently blocked because of missing API token. Should be complete except for that.

**Comment by Tims777** [comment]
Closing as completed now (see last comment).
