### ISSUE TITLE
X (Twitter) as Data Source

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#78]
For SumUp and the training of our AI model it is beneficial, if we can aggregate information from a multitude of different data sources.
For an overview of current data sources see here: [Data Source Table](https://docs.google.com/spreadsheets/d/17W1Koj2aMCUXyq_zYtjvIA3FRmtviDaxpYYIY7xwWWA/edit)

### Done?
* Required fields (orange) in Data Sources table have been filled out
* Implementation is able to retrieve supported features that are not marked as unimplemented

**Comment by Tims777** [comment]
Copied from #50:
**- Twitter (X) API**
 - **Official API**: Twitter offers an API for accessing tweets, user profiles, sending tweets, and more. The API is well-documented and widely used.
 - **Python Integration**: Libraries like `tweepy` make it easy to interact with the Twitter API using Python. It provides methods for most Twitter API endpoints.

**Comment by ultiwinter** [comment]
Berkay and I did some research and found out that Twitter (X) primarily uses usernames as identifiers to retrieve user information. Unfortunately, directly searching for users by their full names isn't supported in the Twitter API.
Documentation: https://docs.tweepy.org/en/stable/api.html#follow-search-and-get-users

**Comment by luccalb** [comment]
Maybe after parsing the website (if there is one) we can extract the X username

**Comment by Tims777** [comment]
That would certainly be possible. However, if we already have the website, how much more information can we obtain from Twitter in relation to how much effort it is to implement that?

**Comment by Tims777** [comment]
Closing this as not planned, as there is currently no perspective, how this could provide a lot of value to SumUp.
