### ISSUE TITLE
Simplify Reports

### ISSUE THREAD

**Issue by NicoHambauer** [amosproj/amos2023ws06-sales-lead-qualifier#81]
Reports should be really simple to read and understand for sales agents (in a few seconds).

Only include crucial information - according to Andi this would be:
* Contact details (name, phone number)
* Google Maps Star Rating (1 to 5)
* Overall review sentiment (see #84)
* Some metric(s) for quality of reviews (see #91)
* Number of potential clients (see #92)
* Business type (from Google Maps API #105 or from elsewhere #85)
* Average of all other indicators

### Implementation Notes
* Do not lay importance on the design, this can be plain text.
* Consider using the same scale (e.g. 0-1) for all features

### Acceptance Criteria
* The report is generated according to the criteria outlined above.
* It is easy to add or remove features from the report, if the demand changes.

**Comment by Tims777** [comment]
Degrading priority to normal for now.
