### ISSUE TITLE
Sentiment analysis

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#84]
Andi wants to have an analysis of the overall review sentiment included in the lead report. GPT should be able to generate such a review sentiment from the given reviews.

### Implementation Notes
We need to either retrieve them in the process or store them first!
Keep consistency in mind. Should not be much of an issue with GPT (in contrast to ChatGPT).

### Done?
When provided with all or some reviews for a given lead, GPT will be run to automatically generate a sentiment analysis (number on a scale e.g. -1 to 1).

**Comment by rbbozkurt** [comment]
After the review of article Felix sent about GPT on sentiment analysis, in which GPT is  actually promising in sentiment analysis, and talk with Andi regarding the expenses, I will be implementing the analysis using GPT.
