### ISSUE TITLE
Setup CI / CD pipelines

### ISSUE THREAD

**Issue by Tims777** [amosproj/amos2023ws06-sales-lead-qualifier#9]
Initial setup of pipeline to be refined while the project is developing.

**Comment by luccalb** [comment]
Waiting for #3

**Comment by luccalb** [comment]
Implement the following stages:

- [ ] Install Dependencies (using pipenv)
- [ ] Lint (using flake8)
- [ ] Test (using pytest)

Following stages could be added later on:

- E2E testing (requires a dev environment to deploy changes to)
- Deployment to Production
